// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Flashtime() {
  return window['go']['service']['App']['Flashtime']();
}

export function Gettestjson() {
  return window['go']['service']['App']['Gettestjson']();
}

export function Greet(arg1) {
  return window['go']['service']['App']['Greet'](arg1);
}
