// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Flashtime() {
  return window['go']['service']['App']['Flashtime']();
}

export function GetALLLang() {
  return window['go']['service']['App']['GetALLLang']();
}

export function GetCurrentLang() {
  return window['go']['service']['App']['GetCurrentLang']();
}

export function GetLangPack() {
  return window['go']['service']['App']['GetLangPack']();
}

export function GetLangTextMap() {
  return window['go']['service']['App']['GetLangTextMap']();
}

export function GetLogFileContent(arg1) {
  return window['go']['service']['App']['GetLogFileContent'](arg1);
}

export function GetLogFiles() {
  return window['go']['service']['App']['GetLogFiles']();
}

export function GetLogLevel() {
  return window['go']['service']['App']['GetLogLevel']();
}

export function GetProcessName() {
  return window['go']['service']['App']['GetProcessName']();
}

export function GetSystemInfo() {
  return window['go']['service']['App']['GetSystemInfo']();
}

export function Gettestjson() {
  return window['go']['service']['App']['Gettestjson']();
}

export function Greet(arg1) {
  return window['go']['service']['App']['Greet'](arg1);
}

export function Notify(arg1, arg2) {
  return window['go']['service']['App']['Notify'](arg1, arg2);
}

export function OpenFileSelect() {
  return window['go']['service']['App']['OpenFileSelect']();
}

export function OpenFolderSelect() {
  return window['go']['service']['App']['OpenFolderSelect']();
}

export function ReadFileContent(arg1) {
  return window['go']['service']['App']['ReadFileContent'](arg1);
}

export function SaveFileSelect() {
  return window['go']['service']['App']['SaveFileSelect']();
}

export function SetLanguage(arg1) {
  return window['go']['service']['App']['SetLanguage'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['service']['App']['SetLogLevel'](arg1);
}

export function WindowClose() {
  return window['go']['service']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['service']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['service']['App']['WindowToggleMaximise']();
}

export function WriteFileContent(arg1, arg2) {
  return window['go']['service']['App']['WriteFileContent'](arg1, arg2);
}
