// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {global} from '../models';
import {service} from '../models';

export function Flashtime():Promise<void>;

export function GetALLLang():Promise<Array<global.LanguageInfo>>;

export function GetCurrentLang():Promise<string>;

export function GetLangPack():Promise<global.LanguagePack>;

export function GetLangTextMap():Promise<Record<string, string>>;

export function GetLogFileContent(arg1:string):Promise<string>;

export function GetLogFiles():Promise<Array<string>>;

export function GetLogLevel():Promise<string>;

export function GetProcessName():Promise<string>;

export function GetSystemInfo():Promise<service.SystemInfo>;

export function Gettestjson():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenFileSelect():Promise<string>;

export function OpenFolderSelect():Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function SaveFileSelect():Promise<string>;

export function SetLanguage(arg1:string):Promise<boolean>;

export function SetLogLevel(arg1:string):Promise<boolean>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;

export function WriteFileContent(arg1:string,arg2:string):Promise<boolean>;
